## Numpy

In [1]:
import numpy as np

In [2]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [6]:
np.array([[1,2,3], [4,5,6], [6,7,8]])

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

- 범위를 지정해 배열 생성

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)