## Numpy

In [2]:
import numpy as np

In [2]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [6]:
np.array([[1,2,3], [4,5,6], [6,7,8]])

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

- 범위를 지정해 배열 생성

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.rand(3,4)

array([[0.81759633, 0.53529013, 0.86489455, 0.61932087],
       [0.01755   , 0.22496123, 0.47875467, 0.40191067],
       [0.21469999, 0.68883747, 0.74361485, 0.00490989]])

In [9]:
np.random.rand()

0.535762042759473

In [11]:
np.random.rand(3,3,4)

array([[[0.76681603, 0.42301659, 0.8279901 , 0.48463487],
        [0.74423635, 0.38283117, 0.76139255, 0.07018349],
        [0.07864865, 0.19250838, 0.44907096, 0.32640752]],

       [[0.04617136, 0.03698253, 0.00860332, 0.98233137],
        [0.97871734, 0.35325122, 0.09245074, 0.5879321 ],
        [0.20971554, 0.19308645, 0.92306917, 0.89515891]],

       [[0.58344711, 0.26724913, 0.88045236, 0.94114053],
        [0.08359315, 0.27069747, 0.9180672 , 0.0567203 ],
        [0.74725846, 0.47152945, 0.03886815, 0.23065857]]])

In [2]:
import numpy as np
np.random.randint(10, size=(3, 4))

array([[0, 6, 4, 6],
       [0, 4, 7, 4],
       [4, 2, 2, 3]])

In [3]:
np.random.randint(1, 30)

13

In [4]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [5]:
arr1 + arr2

array([11, 22, 33, 44])

In [6]:
arr1 > 20

array([False, False,  True,  True])

In [8]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [9]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [10]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [11]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [12]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

## Pandas

In [14]:
import pandas as pd

In [16]:
s1 = pd.Series([10, 20, 30, 40, 50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [17]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [18]:
s3 = pd.Series([np.nan, 10, 30])

In [19]:
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [3]:
import pandas as pd

s5 = pd.Series({'국어': 100, '수학': ' 90', '영어': 95})
s5

국어    100
수학     90
영어     95
dtype: object

In [4]:
pd.date_range(start='2023-11-01', end='2023-11-10')

DatetimeIndex(['2023-11-01', '2023-11-02', '2023-11-03', '2023-11-04',
               '2023-11-05', '2023-11-06', '2023-11-07', '2023-11-08',
               '2023-11-09', '2023-11-10'],
              dtype='datetime64[ns]', freq='D')

In [5]:
pd.date_range(start='2023-11-15', periods=7)

DatetimeIndex(['2023-11-15', '2023-11-16', '2023-11-17', '2023-11-18',
               '2023-11-19', '2023-11-20', '2023-11-21'],
              dtype='datetime64[ns]', freq='D')

In [6]:
pd.date_range(start='2023-01-01', periods=5, freq='W')

DatetimeIndex(['2023-01-01', '2023-01-08', '2023-01-15', '2023-01-22',
               '2023-01-29'],
              dtype='datetime64[ns]', freq='W-SUN')

In [7]:
pd.date_range(start='2023-01-01', periods=7, freq='BM')

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-28',
               '2023-05-31', '2023-06-30', '2023-07-31'],
              dtype='datetime64[ns]', freq='BM')

In [8]:
pd.date_range(start='2020-01-01', periods=7, freq='QS')

DatetimeIndex(['2020-01-01', '2020-04-01', '2020-07-01', '2020-10-01',
               '2021-01-01', '2021-04-01', '2021-07-01'],
              dtype='datetime64[ns]', freq='QS-JAN')

In [9]:
pd.DataFrame([[1,2,3,], [4,5,6], [7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
import numpy as np
import pandas as pd

data_list = np.array([[10,20,30], [40,50,60], [70,80,90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [11]:
data = np.array([[1,2,3,], [4,5,6], [7,8,9], [10,11,12]])
index_date = pd.date_range('2019-09-01', periods=4)
column_list = ['A', 'B', 'C']
pd.DataFrame(data, index=index_date, columns=column_list)

A   B   C
2019-09-01   1   2   3
2019-09-02   4   5   6
2019-09-03   7   8   9
2019-09-04  10  11  12

In [12]:
table_data = {'연도': [2015, 2016, 2016, 2017, 2017],
              '지사': ['한국', '한국', '미국', '한국', '미국'],
              '고객 수': [200, 250, 450, 300, 500]}
table_data

{'연도': [2015, 2016, 2016, 2017, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객 수': [200, 250, 450, 300, 500]}

In [13]:
pd.DataFrame(table_data)

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [14]:
df = pd.DataFrame(table_data)

In [15]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
df.columns

Index(['연도', '지사', '고객 수'], dtype='object')

In [17]:
df.values

array([[2015, '한국', 200],
       [2016, '한국', 250],
       [2016, '미국', 450],
       [2017, '한국', 300],
       [2017, '미국', 500]], dtype=object)